### ISSUE TITLE
EpicMiddleware RxJava2

### ISSUE THREAD

**Issue by sandsaber** [Yarikx/reductor#29]
Hi,
I noticed that Epics currently have done only on rx1, can you push version rx2 version also. Thanks!

**Comment by Yarikx** [comment]
Yes, sure. Will add it soon.

**Comment by Yarikx** [comment]
Added module for Reductor-observable compatible with RxJava2
https://github.com/Yarikx/reductor/tree/master/reductor-observable-rxjava2
https://bintray.com/yarikx/Reductor/ReductorObservableRxJava2

Should soon be available in jcenter

**Comment by sandsaber** [comment]
Thanks! Work like charm
