### ISSUE TITLE
Side Effects

### ISSUE THREAD

**Issue by jQrgen** [Yarikx/reductor#40]
Heya

How can we go about implementing Side Effects using reductor library? 

> ... we probably want that our app has in disk persistence using a DB, and/or we want to add a network layer so we can sync our data to the cloud. This is done by side effects.

The concept is copied from [this](https://proandroiddev.com/unidirectional-data-flow-on-android-the-blog-post-part-1-cadcf88c72f5) blogpost

As far as i can see the closest we can get is to subscribe to the store and have side-effects automatically updating firebase in that way.

**Comment by dector** [comment]
In Redux definition [Reducer](https://redux.js.org/glossary#reducer) is pure function so it can't have side effects. [Middleware](https://redux.js.org/glossary#middleware) is used instead.

Take a look at [this article](https://jayrambhia.com/blog/android-redux-middleware) for details.

Also you can take a look and android-oriented solution from [Cesar Valiente (youtube)](https://www.youtube.com/watch?v=hWdxankV0O0)

**Comment by jQrgen** [comment]
Thanks
