### ISSUE TITLE
[Question] listener may be called after unsubscribe?

### ISSUE THREAD

**Issue by tmtron** [Yarikx/reductor#9]
when looking at [Store<State>](https://github.com/Yarikx/reductor/blob/v0.10.0/lib/src/main/java/com/yheriatovych/reductor/Store.java#L13), I think it is like this:
- the [Cancelable](https://github.com/Yarikx/reductor/blob/v0.10.0/lib/src/main/java/com/yheriatovych/reductor/Cancelable.java) lambda (that is returned from [subscribe()](https://github.com/Yarikx/reductor/blob/v0.10.0/lib/src/main/java/com/yheriatovych/reductor/Store.java#L103)) will remove the listener from [listeners](https://github.com/Yarikx/reductor/blob/v0.10.0/lib/src/main/java/com/yheriatovych/reductor/Store.java#L18)
- `listeners` is a [CopyOnWriteArrayList](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) - so the [for loop](https://github.com/Yarikx/reductor/blob/v0.10.0/lib/src/main/java/com/yheriatovych/reductor/Store.java#L41) in `dispatchAction()` may still iterate over the "old" list and the `listener` may be called after it has already unsubscribed

is this correct?  
if so, then it should at least be mentioned in the doc, because it is not something a user would expect, right?

**Comment by Yarikx** [comment]
Hi, good question.
Yes. The idea was to keep the Redux semantics as close as possible.
http://redux.js.org/docs/api/Store.html#subscribelistener
> The subscriptions are snapshotted just before every dispatch() call. If you subscribe or unsubscribe while the listeners are being invoked, this will not have any effect on the dispatch() that is currently in progress. However, the next dispatch() call, whether nested or not, will use a more recent snapshot of the subscription list.

This allows calling `cancel` while dispatch is still in progress.

But you are right about mentioning it in docs. 
If you want you can submit PR.

**Comment by tmtron** [comment]
hi, thanks for the fast response.

I was not aware, that Conductor is so close to Redux. In this case, I guess that it is enough to know, that the redux.js docs will apply to Conductor code (unless otherwise noted).

Thanks

**Comment by Yarikx** [comment]
Conductor is different Android library, not related to Redux
